### ISSUE TITLE
Change deprecated df.append to pd.concat

### ISSUE THREAD

**Issue by kwinkunks** [equinor/open_petro_elastic#25]
Tests throw warning with Pandas v1.5.2:

```The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.```

I think they are all coming from line 189 in `__main__.py`.

**Comment by eivindjahren** [comment]
This was fixed in https://github.com/equinor/open_petro_elastic/commit/40af557b42031e7f756580d104af5abd73cae258
